### ISSUE TITLE
Add new Bulkiness key

### ISSUE THREAD

**Issue by felipeZ** [nlesc-nano/flamingo#6]
## Change
Include new [CAT bulkiness options](https://github.com/nlesc-nano/CAT/pull/175)

**Comment by BvB93** [comment]
Link to the relevant readthedocs page: https://cat.readthedocs.io/en/latest/4_optional.html#optional.qd.bulkiness.

**Comment by felipeZ** [comment]
Thanks @BvB93!

**Comment by felipeZ** [comment]
solved via #7
